import oracledb


def ssh_aksesuar_isemri_fromOraDB(month, year):
    username = "USR_YUCE_DOGANO"
    userpwd = "qxBhjm0rUA"
    host = "10.113.197.4"
    port = 1521
    service_name = "DOTODWHDBP1"

    dsn = f'{username}/{userpwd}@{host}:{port}/{service_name}'
    connection = oracledb.connect(dsn)

    query = f"""
    SELECT
        case YUCE_DM.TBL_DW_SPR_PART_CATALOG.FK_FIRM_ID when 0 then YUCE_DM.TBL_DW_SPR_PART_CATALOG.ORDER_PART_TYPE_EXPLANATION else 'Harici Parça' END AS tip ,
        TO_CHAR(YUCE_DM.TBL_DW_ASX_WORK_ORDER_DETAIL.INVOICE_DATE, 'DD.MM.YYYY') AS INVOICE_DATE,
        EXTRACT (YEAR FROM YUCE_DM.TBL_DW_ASX_WORK_ORDER_DETAIL.INVOICE_DATE) INVOICE_YEAR,
        EXTRACT (MONTH FROM YUCE_DM.TBL_DW_ASX_WORK_ORDER_DETAIL.INVOICE_DATE) INVOICE_MONTH,
    SUM(YUCE_DM.TBL_DW_ASX_WORK_ORDER_DETAIL.NET_AMOUNT) AS total_amount
    
    FROM
      YUCE_DM.TBL_DW_ASX_WORK_ORDER_DETAIL
      INNER JOIN YUCE_DM.TBL_DW_ASX_WORK_ORDER ON (YUCE_DM.TBL_DW_ASX_WORK_ORDER.WORK_ORDER_ID=YUCE_DM.TBL_DW_ASX_WORK_ORDER_DETAIL.FK_WORK_ORDER_ID)
      LEFT OUTER JOIN YUCE_DM.TBL_DW_SPR_PART_CATALOG ON (YUCE_DM.TBL_DW_SPR_PART_CATALOG.PART_NUMBER=UPPER(YUCE_DM.TBL_DW_ASX_WORK_ORDER_DETAIL.DETAIL_CODE) and YUCE_DM.TBL_DW_ASX_WORK_ORDER_DETAIL.WORK_ORDER_DETAIL_TYPE='Parça')
    WHERE
    EXTRACT(YEAR FROM YUCE_DM.TBL_DW_ASX_WORK_ORDER_DETAIL.INVOICE_DATE)={year}
        AND
        YUCE_DM.TBL_DW_ASX_WORK_ORDER_DETAIL.WORK_ORDER_DETAIL_TYPE  IN  ( 'Parça' )
      AND
      (  YUCE_DM.TBL_DW_ASX_WORK_ORDER.fk_work_order_status_id != 8 )
      AND  
      CASE YUCE_DM.TBL_DW_SPR_PART_CATALOG.FK_FIRM_ID WHEN 0 THEN
    YUCE_DM.TBL_DW_SPR_PART_CATALOG.ORDER_PART_TYPE_EXPLANATION ELSE 'Harici Parça' END IN ('Skoda Aksesuar ','Skoda Butik')
    
    GROUP BY
        case YUCE_DM.TBL_DW_SPR_PART_CATALOG.FK_FIRM_ID when 0 then YUCE_DM.TBL_DW_SPR_PART_CATALOG.ORDER_PART_TYPE_EXPLANATION else 'Harici Parça' end ,
        YUCE_DM.TBL_DW_ASX_WORK_ORDER_DETAIL.INVOICE_DATE,
        EXTRACT (YEAR FROM YUCE_DM.TBL_DW_ASX_WORK_ORDER_DETAIL.INVOICE_DATE) ,
        EXTRACT (MONTH FROM YUCE_DM.TBL_DW_ASX_WORK_ORDER_DETAIL.INVOICE_DATE)
    ORDER BY INVOICE_MONTH
    """

    cursor = connection.cursor()
    cursor.execute(query)

    result = cursor.fetchall()
    days_list = []
    tl_list = []

    for res in result:
        if res[3] == month:
          if res[1][:2][0] == "0":
              days_list.append(res[1][1:2])
          else:
              days_list.append(res[1][:2])
          tl_list.append(round(res[4]))

    sales_sum = {}
    for day, sale in zip(days_list, tl_list):
        if day in sales_sum:
            sales_sum[day] += sale
        else:
            sales_sum[day] = sale
    days_aslist_final = list(sales_sum.keys())
    tlGelir_aslist_final = list(sales_sum.values())

    return days_aslist_final, tlGelir_aslist_final

def ssh_aksesuar_banko_fromOraDB(month, year):
    username = "USR_YUCE_DOGANO"
    userpwd = "qxBhjm0rUA"
    host = "10.113.197.4"
    port = 1521
    service_name = "DOTODWHDBP1"

    dsn = f'{username}/{userpwd}@{host}:{port}/{service_name}'
    connection = oracledb.connect(dsn)

    query = f"""
    SELECT
    TO_CHAR(SS.INVOICE_DATE, 'DD.MM.YYYY') AS INVOICE_DATE,
      EXTRACT(YEAR FROM SS.INVOICE_DATE) YEAR_INVOICE_DATE,
      EXTRACT(MONTH FROM SS.INVOICE_DATE) MONTH_INVOICE_DATE,
    SUM(SS.NET_TRL_AMOUNT) AS total_amount
    FROM YUCE_DM.TBL_DW_SPR_RPT_PART_COUNTER_SALES_SUMMARY SS
    WHERE
        EXTRACT(YEAR FROM SS.INVOICE_DATE) = {year}
        AND
        SS.ITEM_TYPE_EXPLANATION IN ('Skoda Aksesuar ','Skoda Butik')
        AND
        SS.DATA_TYPE_ID  =  1
        AND
        SS.INVOICE_SYSTEM_NO  Is Not NULL
        
      GROUP BY
      SS.INVOICE_DATE,
      EXTRACT(YEAR FROM SS.INVOICE_DATE) ,
      EXTRACT(MONTH FROM SS.INVOICE_DATE)
      ORDER BY MONTH_INVOICE_DATE
    """

    cursor = connection.cursor()
    cursor.execute(query)

    result = cursor.fetchall()

    days_list = []
    tl_list = []

    for res in result:
        if res[2] == month:
          if res[0][:2][0] == "0":
              days_list.append(res[0][1:2])
          else:
              days_list.append(res[0][:2])
          tl_list.append(round(res[3]))

    return days_list, tl_list

def ssh_aksesuar_total_fromGivenDates_fromOraDB(start_date, end_date):
    username = "USR_YUCE_DOGANO"
    userpwd = "qxBhjm0rUA"
    host = "10.113.197.4"
    port = 1521
    service_name = "DOTODWHDBP1"

    dsn = f'{username}/{userpwd}@{host}:{port}/{service_name}'
    connection = oracledb.connect(dsn)

    query1 = f"""
    SELECT sum(total_amount) AS Tplam FROM  (SELECT
        case YUCE_DM.TBL_DW_SPR_PART_CATALOG.FK_FIRM_ID when 0 then YUCE_DM.TBL_DW_SPR_PART_CATALOG.ORDER_PART_TYPE_EXPLANATION else 'Harici Parça' END AS tip ,
        TO_CHAR(YUCE_DM.TBL_DW_ASX_WORK_ORDER_DETAIL.INVOICE_DATE, 'DD.MM.YYYY') AS INVOICE_DATE,
        EXTRACT (YEAR FROM YUCE_DM.TBL_DW_ASX_WORK_ORDER_DETAIL.INVOICE_DATE) INVOICE_YEAR,
        EXTRACT (MONTH FROM YUCE_DM.TBL_DW_ASX_WORK_ORDER_DETAIL.INVOICE_DATE) INVOICE_MONTH,
    SUM(YUCE_DM.TBL_DW_ASX_WORK_ORDER_DETAIL.NET_AMOUNT) AS total_amount
    
    FROM
      YUCE_DM.TBL_DW_ASX_WORK_ORDER_DETAIL
      INNER JOIN YUCE_DM.TBL_DW_ASX_WORK_ORDER ON (YUCE_DM.TBL_DW_ASX_WORK_ORDER.WORK_ORDER_ID=YUCE_DM.TBL_DW_ASX_WORK_ORDER_DETAIL.FK_WORK_ORDER_ID)
      LEFT OUTER JOIN YUCE_DM.TBL_DW_SPR_PART_CATALOG ON (YUCE_DM.TBL_DW_SPR_PART_CATALOG.PART_NUMBER=UPPER(YUCE_DM.TBL_DW_ASX_WORK_ORDER_DETAIL.DETAIL_CODE) and YUCE_DM.TBL_DW_ASX_WORK_ORDER_DETAIL.WORK_ORDER_DETAIL_TYPE='Parça')
    WHERE YUCE_DM.TBL_DW_ASX_WORK_ORDER_DETAIL.INVOICE_DATE >= TO_DATE('{start_date}', 'DD.MM.YYYY')
  AND YUCE_DM.TBL_DW_ASX_WORK_ORDER_DETAIL.INVOICE_DATE <= TO_DATE('{end_date}', 'DD.MM.YYYY')
 
        AND
        YUCE_DM.TBL_DW_ASX_WORK_ORDER_DETAIL.WORK_ORDER_DETAIL_TYPE  IN  ( 'Parça' )
      AND
      (  YUCE_DM.TBL_DW_ASX_WORK_ORDER.fk_work_order_status_id != 8 )
      AND  
      CASE YUCE_DM.TBL_DW_SPR_PART_CATALOG.FK_FIRM_ID WHEN 0 THEN
    YUCE_DM.TBL_DW_SPR_PART_CATALOG.ORDER_PART_TYPE_EXPLANATION ELSE 'Harici Parça' END IN ('Skoda Aksesuar ','Skoda Butik')
    
    GROUP BY
        case YUCE_DM.TBL_DW_SPR_PART_CATALOG.FK_FIRM_ID when 0 then YUCE_DM.TBL_DW_SPR_PART_CATALOG.ORDER_PART_TYPE_EXPLANATION else 'Harici Parça' end ,
        YUCE_DM.TBL_DW_ASX_WORK_ORDER_DETAIL.INVOICE_DATE,
        EXTRACT (YEAR FROM YUCE_DM.TBL_DW_ASX_WORK_ORDER_DETAIL.INVOICE_DATE) ,
        EXTRACT (MONTH FROM YUCE_DM.TBL_DW_ASX_WORK_ORDER_DETAIL.INVOICE_DATE)
    ORDER BY INVOICE_MONTH)
    """
    query2 = f"""
    SELECT sum(total_amount) AS sum FROM (SELECT
    TO_CHAR(SS.INVOICE_DATE, 'DD.MM.YYYY') AS INVOICE_DATE,
      EXTRACT(YEAR FROM SS.INVOICE_DATE) YEAR_INVOICE_DATE,
      EXTRACT(MONTH FROM SS.INVOICE_DATE) MONTH_INVOICE_DATE,
    SUM(SS.NET_TRL_AMOUNT) AS total_amount
    FROM YUCE_DM.TBL_DW_SPR_RPT_PART_COUNTER_SALES_SUMMARY SS
    WHERE SS.INVOICE_DATE >= TO_DATE('{start_date}', 'DD.MM.YYYY')
      AND SS.INVOICE_DATE <= TO_DATE('{end_date}', 'DD.MM.YYYY')
	AND
        SS.ITEM_TYPE_EXPLANATION IN ('Skoda Aksesuar ','Skoda Butik')
        AND
        SS.DATA_TYPE_ID  =  1
        AND
        SS.INVOICE_SYSTEM_NO  Is Not NULL
       
      GROUP BY
      SS.INVOICE_DATE,
      EXTRACT(YEAR FROM SS.INVOICE_DATE) ,
      EXTRACT(MONTH FROM SS.INVOICE_DATE)
      ORDER BY MONTH_INVOICE_DATE)
    """

    cursor = connection.cursor()
    cursor.execute(query1)
    result1 = cursor.fetchone()[0]
    try:
        result1 = round(result1)
    except:result1=0
    
    cursor.execute(query2)
    result2 = cursor.fetchone()[0]
    try:
        result2 = round(result2)
    except:result2=0
    result = result1 + result2

    return result

def ssh_aksesuar_stok_fromOraDB():
    username = "USR_YUCE_DOGANO"
    userpwd = "qxBhjm0rUA"
    host = "10.113.197.4"
    port = 1521
    service_name = "DOTODWHDBP1"

    dsn = f'{username}/{userpwd}@{host}:{port}/{service_name}'
    connection = oracledb.connect(dsn)

    query = f"""
    SELECT sum(t.Aksesuar) AS sonuc 
    FROM ( 
    SELECT
    YUCE_DM.TBL_DW_SPR_STOCK_MASTER.FK_FIRM_ID,
    --YUCE_DM.TBL_DW_SPR_OTHER_PART_CATALOG.MARINE_SERVICES_BRAND_DEFINITION ,
    YUCE_DM.TBL_DW_SPR_STOCK_MASTER.FIRM_EXPLANATION,
    NVL(YUCE_DM.TBL_DW_SPR_PART_CATALOG.ORDER_PART_TYPE_EXPLANATION,'DİĞER') AS Tip,
    YUCE_DM.TBL_DW_SPR_OTHER_PART_CATALOG.PART_CLASS_EXPLANATION,
    YUCE_DM.TBL_DW_SPR_PART_CATALOG.PART_GROUP_EXPLANATION,
    YUCE_DM.TBL_DW_SPR_PART_CATALOG.PART_NUMBER,
    YUCE_DM.TBL_DW_SPR_PART_CATALOG.PART_DEFINITION_TR,
    YUCE_DM.TBL_DW_SPR_PART_CATALOG.PART_DEFINITION_EN,
    YUCE_DM.TBL_DW_SPR_PART_CATALOG.NEW_PART_NUMBER,
    YUCE_DM.TBL_DW_SPR_DIM_DEPOT_AREA.DEPOT_CODE,
    YUCE_DM.TBL_DW_SPR_DIM_DEPOT_AREA.DEPOT_ZONE_CODE,
    YUCE_DM.TBL_DW_SPR_DIM_DEPOT_AREA.DEPOT_AREA_CODE,
    NVL(YUCE_DM.TBL_DW_SPR_PART_CATALOG.BASIC_UNIT_SHORT_CODE,YUCE_DM.TBL_DW_SPR_OTHER_PART_CATALOG.BASIC_UNIT_SHORT_CODE ),
    YUCE_DM.TBL_DW_SPR_PART_CATALOG.COMMON_PART_GROUP,
    YUCE_DM.TBL_DW_SPR_PART_CATALOG.PREFERRED_SUPPLIER_EXPLANATION,
    SUM(YUCE_DM.TBL_DW_SPR_STOCK_MASTER.TOTAL_INCOMING_QUANTITY - YUCE_DM.TBL_DW_SPR_STOCK_MASTER.TOTAL_OUTGOING_QUANTITY),
    YUCE_DM.TBL_DW_SPR_PART_CATALOG.PART_LIST_PRICE,
    CASE WHEN ( YUCE_DM.TBL_DW_SPR_DIM_DEPOT_AREA.DEPOT_AREA_IS_SELLABLE )=1 THEN YUCE_DM.TBL_DW_SPR_STOCK_MASTER.TOTAL_INCOMING_QUANTITY - YUCE_DM.TBL_DW_SPR_STOCK_MASTER.TOTAL_OUTGOING_QUANTITY-
    YUCE_DM.TBL_DW_SPR_STOCK_MASTER.transfer_reservation_quantity - YUCE_DM.TBL_DW_SPR_STOCK_MASTER.picking_reservation_quantity ELSE 0 END,
    YUCE_DM.TBL_DW_SPR_PART_STOCK_CARD.LAST_AVERAGE_UNIT_COST,
    ( SUM(YUCE_DM.TBL_DW_SPR_STOCK_MASTER.TOTAL_INCOMING_QUANTITY - YUCE_DM.TBL_DW_SPR_STOCK_MASTER.TOTAL_OUTGOING_QUANTITY) )*( YUCE_DM.TBL_DW_SPR_PART_STOCK_CARD.LAST_AVERAGE_UNIT_COST ) AS Aksesuar,
    YUCE_DM.TBL_DW_SPR_PART_CATALOG.VAT_RATIO,
    ( SUM(YUCE_DM.TBL_DW_SPR_STOCK_MASTER.TOTAL_INCOMING_QUANTITY - YUCE_DM.TBL_DW_SPR_STOCK_MASTER.TOTAL_OUTGOING_QUANTITY) )*( NVL(YUCE_DM.TBL_DW_SPR_PART_CATALOG.PART_LIST_PRICE, YUCE_DM.TBL_DW_SPR_OTHER_PART_CATALOG.SALES_PRICE) ),
    CASE WHEN ( YUCE_DM.TBL_DW_SPR_OTHER_PART_CATALOG.IS_REPAIRED_PART )= 0 THEN 'Hayır' WHEN ( YUCE_DM.TBL_DW_SPR_OTHER_PART_CATALOG.IS_REPAIRED_PART )= 1 THEN 'Evet' ELSE ' ' END,
    YUCE_DM.TBL_DW_SPR_PART_CATALOG.PART_FAMILY,
    YUCE_DM.TBL_DW_SPR_PART_CATALOG.COMPONENT_CODE_SCANIA,
    NVL(YUCE_DM.TBL_DW_SPR_PART_CATALOG.PART_DEFINITION_TR, YUCE_DM.TBL_DW_SPR_OTHER_PART_CATALOG.PART_DEFINITION_TR),
    NVL(YUCE_DM.TBL_DW_SPR_PART_CATALOG.PART_LIST_PRICE, YUCE_DM.TBL_DW_SPR_OTHER_PART_CATALOG.SALES_PRICE),
    YUCE_DM.TBL_DW_SPR_STOCK_MASTER.PART_NUMBER,
    CASE YUCE_DM.TBL_DW_SPR_PART_CATALOG.FK_FIRM_ID WHEN 0 THEN 
    YUCE_DM.TBL_DW_SPR_PART_CATALOG.ORDER_PART_TYPE_EXPLANATION ELSE 'Harici Parça' END,
    YUCE_DM.TBL_DW_SPR_PART_CATALOG.FOB_PRICE
    FROM
    YUCE_DM.TBL_DW_SPR_PART_CATALOG FULL OUTER JOIN YUCE_DM.TBL_DW_SPR_PART_STOCK_CARD ON (YUCE_DM.TBL_DW_SPR_PART_CATALOG.PART_NUMBER=YUCE_DM.TBL_DW_SPR_PART_STOCK_CARD.PART_NUMBER)
    LEFT OUTER JOIN YUCE_DM.TBL_DW_SPR_OTHER_PART_CATALOG ON (YUCE_DM.TBL_DW_SPR_OTHER_PART_CATALOG.PART_NUMBER=YUCE_DM.TBL_DW_SPR_PART_STOCK_CARD.PART_NUMBER 
    AND YUCE_DM.TBL_DW_SPR_OTHER_PART_CATALOG.FK_FIRM_ID=YUCE_DM.TBL_DW_SPR_PART_STOCK_CARD.FK_FIRM_ID)
    LEFT OUTER JOIN YUCE_DM.TBL_DW_SPR_STOCK_MASTER ON (YUCE_DM.TBL_DW_SPR_PART_STOCK_CARD.PART_NUMBER=YUCE_DM.TBL_DW_SPR_STOCK_MASTER.PART_NUMBER AND YUCE_DM.TBL_DW_SPR_PART_STOCK_CARD.FK_FIRM_ID=YUCE_DM.TBL_DW_SPR_STOCK_MASTER.FK_FIRM_ID)
    RIGHT OUTER JOIN YUCE_DM.TBL_DW_SPR_DIM_DEPOT_AREA ON (YUCE_DM.TBL_DW_SPR_STOCK_MASTER.FK_FIRM_ID=YUCE_DM.TBL_DW_SPR_DIM_DEPOT_AREA.FK_DEPOT_AREA_FIRM_ID AND YUCE_DM.TBL_DW_SPR_STOCK_MASTER.FK_DEPOT_AREA_ID=YUCE_DM.TBL_DW_SPR_DIM_DEPOT_AREA.DEPOT_AREA_ID)

    WHERE 
    NVL(YUCE_DM.TBL_DW_SPR_PART_CATALOG.ORDER_PART_TYPE_EXPLANATION,'DİĞER') LIKE '%Skoda Aksesuar%'
    AND YUCE_DM.TBL_DW_SPR_STOCK_MASTER.FK_FIRM_ID IN (SELECT FIRM_ID from YUCE_DM.TBL_DW_GEN_DIM_FIRM_TYPE_MAPPING WHERE YS_TYPE_EXPLANATION ='Satış Sonrası Hizmetler')
    GROUP BY
    YUCE_DM.TBL_DW_SPR_STOCK_MASTER.FK_FIRM_ID, 
    --YUCE_DM.TBL_DW_SPR_OTHER_PART_CATALOG.MARINE_SERVICES_BRAND_DEFINITION , 
    YUCE_DM.TBL_DW_SPR_STOCK_MASTER.FIRM_EXPLANATION, 
    NVL(YUCE_DM.TBL_DW_SPR_PART_CATALOG.ORDER_PART_TYPE_EXPLANATION,'DİĞER'), 
    YUCE_DM.TBL_DW_SPR_OTHER_PART_CATALOG.PART_CLASS_EXPLANATION, 
    YUCE_DM.TBL_DW_SPR_PART_CATALOG.PART_GROUP_EXPLANATION, 
    YUCE_DM.TBL_DW_SPR_PART_CATALOG.PART_NUMBER, 
    YUCE_DM.TBL_DW_SPR_PART_CATALOG.PART_DEFINITION_TR, 
    YUCE_DM.TBL_DW_SPR_PART_CATALOG.PART_DEFINITION_EN, 
    YUCE_DM.TBL_DW_SPR_PART_CATALOG.NEW_PART_NUMBER, 
    YUCE_DM.TBL_DW_SPR_DIM_DEPOT_AREA.DEPOT_CODE, 
    YUCE_DM.TBL_DW_SPR_DIM_DEPOT_AREA.DEPOT_ZONE_CODE, 
    YUCE_DM.TBL_DW_SPR_DIM_DEPOT_AREA.DEPOT_AREA_CODE, 
    NVL(YUCE_DM.TBL_DW_SPR_PART_CATALOG.BASIC_UNIT_SHORT_CODE,YUCE_DM.TBL_DW_SPR_OTHER_PART_CATALOG.BASIC_UNIT_SHORT_CODE ), 
    YUCE_DM.TBL_DW_SPR_PART_CATALOG.COMMON_PART_GROUP, 
    YUCE_DM.TBL_DW_SPR_PART_CATALOG.PREFERRED_SUPPLIER_EXPLANATION, 
    YUCE_DM.TBL_DW_SPR_PART_CATALOG.PART_LIST_PRICE, 
    CASE WHEN ( YUCE_DM.TBL_DW_SPR_DIM_DEPOT_AREA.DEPOT_AREA_IS_SELLABLE )=1 THEN YUCE_DM.TBL_DW_SPR_STOCK_MASTER.TOTAL_INCOMING_QUANTITY - YUCE_DM.TBL_DW_SPR_STOCK_MASTER.TOTAL_OUTGOING_QUANTITY-
    YUCE_DM.TBL_DW_SPR_STOCK_MASTER.transfer_reservation_quantity - YUCE_DM.TBL_DW_SPR_STOCK_MASTER.picking_reservation_quantity ELSE 0 END, 
    YUCE_DM.TBL_DW_SPR_PART_STOCK_CARD.LAST_AVERAGE_UNIT_COST, 
    YUCE_DM.TBL_DW_SPR_PART_CATALOG.VAT_RATIO, 
    CASE WHEN ( YUCE_DM.TBL_DW_SPR_OTHER_PART_CATALOG.IS_REPAIRED_PART )= 0 THEN 'Hayır' WHEN ( YUCE_DM.TBL_DW_SPR_OTHER_PART_CATALOG.IS_REPAIRED_PART )= 1 THEN 'Evet' ELSE ' ' END, 
    YUCE_DM.TBL_DW_SPR_PART_CATALOG.PART_FAMILY, 
    YUCE_DM.TBL_DW_SPR_PART_CATALOG.COMPONENT_CODE_SCANIA, 
    NVL(YUCE_DM.TBL_DW_SPR_PART_CATALOG.PART_DEFINITION_TR, YUCE_DM.TBL_DW_SPR_OTHER_PART_CATALOG.PART_DEFINITION_TR), 
    NVL(YUCE_DM.TBL_DW_SPR_PART_CATALOG.PART_LIST_PRICE, YUCE_DM.TBL_DW_SPR_OTHER_PART_CATALOG.SALES_PRICE), 
    YUCE_DM.TBL_DW_SPR_STOCK_MASTER.PART_NUMBER, 
    CASE YUCE_DM.TBL_DW_SPR_PART_CATALOG.FK_FIRM_ID WHEN 0 THEN 
    YUCE_DM.TBL_DW_SPR_PART_CATALOG.ORDER_PART_TYPE_EXPLANATION ELSE 'Harici Parça' END, 
    YUCE_DM.TBL_DW_SPR_PART_CATALOG.FOB_PRICE
    HAVING
    SUM(YUCE_DM.TBL_DW_SPR_STOCK_MASTER.TOTAL_INCOMING_QUANTITY - YUCE_DM.TBL_DW_SPR_STOCK_MASTER.TOTAL_OUTGOING_QUANTITY) > 0
    ) t
    """

    cursor = connection.cursor()
    cursor.execute(query)

    result = cursor.fetchone()
    res = round(result[0])

    return res
  
def ssh_parca_stok_fromOraDB():
    username = "USR_YUCE_DOGANO"
    userpwd = "qxBhjm0rUA"
    host = "10.113.197.4"
    port = 1521
    service_name = "DOTODWHDBP1"

    dsn = f'{username}/{userpwd}@{host}:{port}/{service_name}'
    connection = oracledb.connect(dsn)

    query = f"""
    SELECT sum(t.YedekParca) AS sonuc 
    FROM ( 
    SELECT
    YUCE_DM.TBL_DW_SPR_STOCK_MASTER.FK_FIRM_ID,
    --YUCE_DM.TBL_DW_SPR_OTHER_PART_CATALOG.MARINE_SERVICES_BRAND_DEFINITION ,
    YUCE_DM.TBL_DW_SPR_STOCK_MASTER.FIRM_EXPLANATION,
    NVL(YUCE_DM.TBL_DW_SPR_PART_CATALOG.ORDER_PART_TYPE_EXPLANATION,'DİĞER') AS Tip,
    YUCE_DM.TBL_DW_SPR_OTHER_PART_CATALOG.PART_CLASS_EXPLANATION,
    YUCE_DM.TBL_DW_SPR_PART_CATALOG.PART_GROUP_EXPLANATION,
    YUCE_DM.TBL_DW_SPR_PART_CATALOG.PART_NUMBER,
    YUCE_DM.TBL_DW_SPR_PART_CATALOG.PART_DEFINITION_TR,
    YUCE_DM.TBL_DW_SPR_PART_CATALOG.PART_DEFINITION_EN,
    YUCE_DM.TBL_DW_SPR_PART_CATALOG.NEW_PART_NUMBER,
    YUCE_DM.TBL_DW_SPR_DIM_DEPOT_AREA.DEPOT_CODE,
    YUCE_DM.TBL_DW_SPR_DIM_DEPOT_AREA.DEPOT_ZONE_CODE,
    YUCE_DM.TBL_DW_SPR_DIM_DEPOT_AREA.DEPOT_AREA_CODE,
    NVL(YUCE_DM.TBL_DW_SPR_PART_CATALOG.BASIC_UNIT_SHORT_CODE,YUCE_DM.TBL_DW_SPR_OTHER_PART_CATALOG.BASIC_UNIT_SHORT_CODE ),
    YUCE_DM.TBL_DW_SPR_PART_CATALOG.COMMON_PART_GROUP,
    YUCE_DM.TBL_DW_SPR_PART_CATALOG.PREFERRED_SUPPLIER_EXPLANATION,
    SUM(YUCE_DM.TBL_DW_SPR_STOCK_MASTER.TOTAL_INCOMING_QUANTITY - YUCE_DM.TBL_DW_SPR_STOCK_MASTER.TOTAL_OUTGOING_QUANTITY),
    YUCE_DM.TBL_DW_SPR_PART_CATALOG.PART_LIST_PRICE,
    CASE WHEN ( YUCE_DM.TBL_DW_SPR_DIM_DEPOT_AREA.DEPOT_AREA_IS_SELLABLE )=1 THEN YUCE_DM.TBL_DW_SPR_STOCK_MASTER.TOTAL_INCOMING_QUANTITY - YUCE_DM.TBL_DW_SPR_STOCK_MASTER.TOTAL_OUTGOING_QUANTITY-
    YUCE_DM.TBL_DW_SPR_STOCK_MASTER.transfer_reservation_quantity - YUCE_DM.TBL_DW_SPR_STOCK_MASTER.picking_reservation_quantity ELSE 0 END,
    YUCE_DM.TBL_DW_SPR_PART_STOCK_CARD.LAST_AVERAGE_UNIT_COST,
    ( SUM(YUCE_DM.TBL_DW_SPR_STOCK_MASTER.TOTAL_INCOMING_QUANTITY - YUCE_DM.TBL_DW_SPR_STOCK_MASTER.TOTAL_OUTGOING_QUANTITY) )*( YUCE_DM.TBL_DW_SPR_PART_STOCK_CARD.LAST_AVERAGE_UNIT_COST ) AS YedekParca,
    YUCE_DM.TBL_DW_SPR_PART_CATALOG.VAT_RATIO,
    ( SUM(YUCE_DM.TBL_DW_SPR_STOCK_MASTER.TOTAL_INCOMING_QUANTITY - YUCE_DM.TBL_DW_SPR_STOCK_MASTER.TOTAL_OUTGOING_QUANTITY) )*( NVL(YUCE_DM.TBL_DW_SPR_PART_CATALOG.PART_LIST_PRICE, YUCE_DM.TBL_DW_SPR_OTHER_PART_CATALOG.SALES_PRICE) ),
    CASE WHEN ( YUCE_DM.TBL_DW_SPR_OTHER_PART_CATALOG.IS_REPAIRED_PART )= 0 THEN 'Hayır' WHEN ( YUCE_DM.TBL_DW_SPR_OTHER_PART_CATALOG.IS_REPAIRED_PART )= 1 THEN 'Evet' ELSE ' ' END,
    YUCE_DM.TBL_DW_SPR_PART_CATALOG.PART_FAMILY,
    YUCE_DM.TBL_DW_SPR_PART_CATALOG.COMPONENT_CODE_SCANIA,
    NVL(YUCE_DM.TBL_DW_SPR_PART_CATALOG.PART_DEFINITION_TR, YUCE_DM.TBL_DW_SPR_OTHER_PART_CATALOG.PART_DEFINITION_TR),
    NVL(YUCE_DM.TBL_DW_SPR_PART_CATALOG.PART_LIST_PRICE, YUCE_DM.TBL_DW_SPR_OTHER_PART_CATALOG.SALES_PRICE),
    YUCE_DM.TBL_DW_SPR_STOCK_MASTER.PART_NUMBER,
    CASE YUCE_DM.TBL_DW_SPR_PART_CATALOG.FK_FIRM_ID WHEN 0 THEN 
    YUCE_DM.TBL_DW_SPR_PART_CATALOG.ORDER_PART_TYPE_EXPLANATION ELSE 'Harici Parça' END,
    YUCE_DM.TBL_DW_SPR_PART_CATALOG.FOB_PRICE
    FROM
    YUCE_DM.TBL_DW_SPR_PART_CATALOG FULL OUTER JOIN YUCE_DM.TBL_DW_SPR_PART_STOCK_CARD ON (YUCE_DM.TBL_DW_SPR_PART_CATALOG.PART_NUMBER=YUCE_DM.TBL_DW_SPR_PART_STOCK_CARD.PART_NUMBER)
    LEFT OUTER JOIN YUCE_DM.TBL_DW_SPR_OTHER_PART_CATALOG ON (YUCE_DM.TBL_DW_SPR_OTHER_PART_CATALOG.PART_NUMBER=YUCE_DM.TBL_DW_SPR_PART_STOCK_CARD.PART_NUMBER 
    AND YUCE_DM.TBL_DW_SPR_OTHER_PART_CATALOG.FK_FIRM_ID=YUCE_DM.TBL_DW_SPR_PART_STOCK_CARD.FK_FIRM_ID)
    LEFT OUTER JOIN YUCE_DM.TBL_DW_SPR_STOCK_MASTER ON (YUCE_DM.TBL_DW_SPR_PART_STOCK_CARD.PART_NUMBER=YUCE_DM.TBL_DW_SPR_STOCK_MASTER.PART_NUMBER AND YUCE_DM.TBL_DW_SPR_PART_STOCK_CARD.FK_FIRM_ID=YUCE_DM.TBL_DW_SPR_STOCK_MASTER.FK_FIRM_ID)
    RIGHT OUTER JOIN YUCE_DM.TBL_DW_SPR_DIM_DEPOT_AREA ON (YUCE_DM.TBL_DW_SPR_STOCK_MASTER.FK_FIRM_ID=YUCE_DM.TBL_DW_SPR_DIM_DEPOT_AREA.FK_DEPOT_AREA_FIRM_ID AND YUCE_DM.TBL_DW_SPR_STOCK_MASTER.FK_DEPOT_AREA_ID=YUCE_DM.TBL_DW_SPR_DIM_DEPOT_AREA.DEPOT_AREA_ID)
    WHERE 
    (NVL(YUCE_DM.TBL_DW_SPR_PART_CATALOG.ORDER_PART_TYPE_EXPLANATION, 'DİĞER') LIKE 'Skoda Anahtar%'
    OR NVL(YUCE_DM.TBL_DW_SPR_PART_CATALOG.ORDER_PART_TYPE_EXPLANATION, 'DİĞER') LIKE 'YS Motor Yağları%'
    OR NVL(YUCE_DM.TBL_DW_SPR_PART_CATALOG.ORDER_PART_TYPE_EXPLANATION, 'DİĞER') LIKE 'Skoda Etiket%'
    OR NVL(YUCE_DM.TBL_DW_SPR_PART_CATALOG.ORDER_PART_TYPE_EXPLANATION, 'DİĞER') LIKE 'Yedek Parça'
    OR NVL(YUCE_DM.TBL_DW_SPR_PART_CATALOG.ORDER_PART_TYPE_EXPLANATION, 'DİĞER') LIKE 'Skoda Yedek Parça%')
    AND YUCE_DM.TBL_DW_SPR_STOCK_MASTER.FK_FIRM_ID IN (SELECT FIRM_ID from YUCE_DM.TBL_DW_GEN_DIM_FIRM_TYPE_MAPPING WHERE YS_TYPE_EXPLANATION ='Satış Sonrası Hizmetler')
    AND YUCE_DM.TBL_DW_SPR_PART_CATALOG.COMMON_PART_GROUP IN ('Skoda Ozel','Ortak Parcalar')
    GROUP BY
    YUCE_DM.TBL_DW_SPR_STOCK_MASTER.FK_FIRM_ID, 
    --YUCE_DM.TBL_DW_SPR_OTHER_PART_CATALOG.MARINE_SERVICES_BRAND_DEFINITION , 
    YUCE_DM.TBL_DW_SPR_STOCK_MASTER.FIRM_EXPLANATION, 
    NVL(YUCE_DM.TBL_DW_SPR_PART_CATALOG.ORDER_PART_TYPE_EXPLANATION,'DİĞER'), 
    YUCE_DM.TBL_DW_SPR_OTHER_PART_CATALOG.PART_CLASS_EXPLANATION, 
    YUCE_DM.TBL_DW_SPR_PART_CATALOG.PART_GROUP_EXPLANATION, 
    YUCE_DM.TBL_DW_SPR_PART_CATALOG.PART_NUMBER, 
    YUCE_DM.TBL_DW_SPR_PART_CATALOG.PART_DEFINITION_TR, 
    YUCE_DM.TBL_DW_SPR_PART_CATALOG.PART_DEFINITION_EN, 
    YUCE_DM.TBL_DW_SPR_PART_CATALOG.NEW_PART_NUMBER, 
    YUCE_DM.TBL_DW_SPR_DIM_DEPOT_AREA.DEPOT_CODE, 
    YUCE_DM.TBL_DW_SPR_DIM_DEPOT_AREA.DEPOT_ZONE_CODE, 
    YUCE_DM.TBL_DW_SPR_DIM_DEPOT_AREA.DEPOT_AREA_CODE, 
    NVL(YUCE_DM.TBL_DW_SPR_PART_CATALOG.BASIC_UNIT_SHORT_CODE,YUCE_DM.TBL_DW_SPR_OTHER_PART_CATALOG.BASIC_UNIT_SHORT_CODE ), 
    YUCE_DM.TBL_DW_SPR_PART_CATALOG.COMMON_PART_GROUP, 
    YUCE_DM.TBL_DW_SPR_PART_CATALOG.PREFERRED_SUPPLIER_EXPLANATION, 
    YUCE_DM.TBL_DW_SPR_PART_CATALOG.PART_LIST_PRICE, 
    CASE WHEN ( YUCE_DM.TBL_DW_SPR_DIM_DEPOT_AREA.DEPOT_AREA_IS_SELLABLE )=1 THEN YUCE_DM.TBL_DW_SPR_STOCK_MASTER.TOTAL_INCOMING_QUANTITY - YUCE_DM.TBL_DW_SPR_STOCK_MASTER.TOTAL_OUTGOING_QUANTITY-
    YUCE_DM.TBL_DW_SPR_STOCK_MASTER.transfer_reservation_quantity - YUCE_DM.TBL_DW_SPR_STOCK_MASTER.picking_reservation_quantity ELSE 0 END, 
    YUCE_DM.TBL_DW_SPR_PART_STOCK_CARD.LAST_AVERAGE_UNIT_COST, 
    YUCE_DM.TBL_DW_SPR_PART_CATALOG.VAT_RATIO, 
    CASE WHEN ( YUCE_DM.TBL_DW_SPR_OTHER_PART_CATALOG.IS_REPAIRED_PART )= 0 THEN 'Hayır' WHEN ( YUCE_DM.TBL_DW_SPR_OTHER_PART_CATALOG.IS_REPAIRED_PART )= 1 THEN 'Evet' ELSE ' ' END, 
    YUCE_DM.TBL_DW_SPR_PART_CATALOG.PART_FAMILY, 
    YUCE_DM.TBL_DW_SPR_PART_CATALOG.COMPONENT_CODE_SCANIA, 
    NVL(YUCE_DM.TBL_DW_SPR_PART_CATALOG.PART_DEFINITION_TR, YUCE_DM.TBL_DW_SPR_OTHER_PART_CATALOG.PART_DEFINITION_TR), 
    NVL(YUCE_DM.TBL_DW_SPR_PART_CATALOG.PART_LIST_PRICE, YUCE_DM.TBL_DW_SPR_OTHER_PART_CATALOG.SALES_PRICE), 
    YUCE_DM.TBL_DW_SPR_STOCK_MASTER.PART_NUMBER, 
    CASE YUCE_DM.TBL_DW_SPR_PART_CATALOG.FK_FIRM_ID WHEN 0 THEN 
    YUCE_DM.TBL_DW_SPR_PART_CATALOG.ORDER_PART_TYPE_EXPLANATION ELSE 'Harici Parça' END, 
    YUCE_DM.TBL_DW_SPR_PART_CATALOG.FOB_PRICE
    HAVING
    SUM(YUCE_DM.TBL_DW_SPR_STOCK_MASTER.TOTAL_INCOMING_QUANTITY - YUCE_DM.TBL_DW_SPR_STOCK_MASTER.TOTAL_OUTGOING_QUANTITY) > 0
    ) t
    """

    cursor = connection.cursor()
    cursor.execute(query)

    result = cursor.fetchone()
    res = round(result[0])

    return res

def ssh_randevulu_servis_girisi_fromGivenDates_fromOraDB(start_date, end_date):
    username = "USR_YUCE_DOGANO"
    userpwd = "qxBhjm0rUA"
    host = "10.113.197.4"
    port = 1521
    service_name = "DOTODWHDBP1"

    dsn = f'{username}/{userpwd}@{host}:{port}/{service_name}'
    connection = oracledb.connect(dsn)

    query = f"""
    SELECT sum(total) AS randevulu from (SELECT
    COUNT(WORK_ORDER_ID) AS total,
    FIRM_CODE,
    FK_FIRM_ID,
    EXTRACT(YEAR FROM CREATE_DATE) AS Year_,
    EXTRACT(MONTH FROM CREATE_DATE) AS MONTH_
    FROM
    YUCE_DM.TBL_DW_ASX_WORK_ORDER tdawo
    WHERE
    FK_APPOINTMENT_ID <> 0
    AND tdawo.CREATE_DATE >= TO_DATE('{start_date}', 'DD.MM.YYYY')
    AND tdawo.CREATE_DATE < TO_DATE('{end_date}', 'DD.MM.YYYY')
    GROUP BY
    --COUNT(WORK_ORDER_ID),
    FIRM_CODE,
    FK_FIRM_ID,
    EXTRACT(YEAR FROM CREATE_DATE),
    EXTRACT(MONTH FROM CREATE_DATE)
    )
    """
    cursor = connection.cursor()
    cursor.execute(query)
    result = cursor.fetchone()[0]
    try:
        result = round(result)
    except:pass
    
    return result

def ssh_servis_girisi_fromGivenDates_fromOraDB(start_date, end_date):
    username = "USR_YUCE_DOGANO"
    userpwd = "qxBhjm0rUA"
    host = "10.113.197.4"
    port = 1521
    service_name = "DOTODWHDBP1"

    dsn = f'{username}/{userpwd}@{host}:{port}/{service_name}'
    connection = oracledb.connect(dsn)
    query = f"""
    SELECT  DISTINCT
    COUNT (WORK_ORDER.WORK_ORDER_ID) AS TOTAL_WORK_ORDER,
    COUNT(CASE WHEN FK_APPOINTMENT_ID <> '0' THEN WORK_ORDER_ID END) AS Withappointment
    
    FROM
    YUCE_DM.TBL_DW_ASX_WORK_ORDER WORK_ORDER
    WHERE
        WORK_ORDER.fk_work_order_status_id != 8
        AND WORK_ORDER.WORK_ORDER_STATUS_EXPLANATION <> 'Askıda'
        AND WORK_ORDER.BRAND_DEFINITION IN ('Skoda')
        AND WORK_ORDER.PDI_STATUS_EXPLANATION IN ('YOK')
        AND WORK_ORDER.CREATE_DATE BETWEEN TO_DATE('{start_date}', 'DD.MM.YYYY') AND TO_DATE('{end_date}', 'DD.MM.YYYY')
    """
    
    cursor = connection.cursor()
    cursor.execute(query)
    result = cursor.fetchone()
    servis_giris = result[0]
    randevulu_servis_giris = result[1]

    return servis_giris, randevulu_servis_giris
    
def ssh_musteri_sikayet_fromGivenDates_fromOraDB(start_date, end_date, year):
    username = "USR_YUCE_DOGANO"
    userpwd = "qxBhjm0rUA"
    host = "10.113.197.4"
    port = 1521
    service_name = "DOTODWHDBP1"

    dsn = f'{username}/{userpwd}@{host}:{port}/{service_name}'
    connection = oracledb.connect(dsn)

    query = f"""
    SELECT T1.FIRM_CODE,
       T1.WORK_ORDER_COUNT,
       T2.CONTACT_COUNT,
       T2.CONTACT_COUNT / T1.WORK_ORDER_COUNT AS CONTACT_WORK_ORDER_RATIO,
       '{year}' AS YEAR
    FROM (SELECT TDAWO.FIRM_CODE,
                COUNT(TDAWO.WORK_ORDER_ID) AS WORK_ORDER_COUNT
        FROM YUCE_DM.TBL_DW_ASX_WORK_ORDER TDAWO
        WHERE TDAWO.CREATE_DATE >= TO_DATE('{start_date}', 'DD.MM.YYYY')
            AND TDAWO.CREATE_DATE < TO_DATE('{end_date}', 'DD.MM.YYYY')
            AND TDAWO.FK_WORK_ORDER_STATUS_ID <> 8
        GROUP BY TDAWO.FIRM_CODE) T1
    LEFT JOIN (SELECT DISTINCT TDCRCI.FIRM_CODE,
                            COUNT(DISTINCT TDCRCI.CONTACT_CODE) AS CONTACT_COUNT
            FROM YUCE_DM.TBL_DW_CUS_RPT_CONTACT_INFO TDCRCI
            WHERE TDCRCI.REASON = 'Şikayet'
                AND (UPPER(TDCRCI.SUBJECT_EXPLANATION) NOT LIKE '%BINEK%'
                    AND UPPER(TDCRCI.SUBJECT_EXPLANATION) NOT LIKE 'SAFE%'
                    AND UPPER(TDCRCI.SUBJECT_EXPLANATION) NOT LIKE 'CP%'
                    AND UPPER(TDCRCI.SUBJECT_EXPLANATION) NOT LIKE 'SAFE CP%'
                    AND UPPER(TDCRCI.SUBJECT_EXPLANATION) NOT LIKE ',SAFE CP%'
                    AND UPPER(TDCRCI.SUBJECT_EXPLANATION) NOT LIKE '%BİLEŞEN%'
                    AND UPPER(TDCRCI.SUBJECT_EXPLANATION) NOT LIKE ' BİLEŞEN%'
                    AND UPPER(TDCRCI.SUBJECT_EXPLANATION) NOT LIKE '%,BİLEŞEN%'
                    AND UPPER(TDCRCI.SUBJECT_EXPLANATION) NOT LIKE '%,SAFE%'
                    AND UPPER(TDCRCI.SUBJECT_EXPLANATION) NOT LIKE '%SAFECB%'
                    AND UPPER(TDCRCI.SUBJECT_EXPLANATION) NOT LIKE '%SAFE CB%'
                    AND UPPER(TDCRCI.SUBJECT_EXPLANATION) NOT LIKE '%SAFE CF%'
                    AND UPPER(TDCRCI.SUBJECT_EXPLANATION) NOT LIKE '%SAFE COP%'
                    AND UPPER(TDCRCI.SUBJECT_EXPLANATION) NOT LIKE '%SAFE - CP%'
                    AND UPPER(TDCRCI.SUBJECT_EXPLANATION) NOT LIKE '% SAFE %'
                    AND UPPER(TDCRCI.SUBJECT_EXPLANATION) NOT LIKE '%BİLEŞEN%'
                    AND UPPER(TDCRCI.SUBJECT_EXPLANATION) NOT LIKE '%SACE CP%'
                    AND UPPER(TDCRCI.SUBJECT_EXPLANATION) NOT LIKE '%CACE CP%'
                    AND UPPER(TDCRCI.SUBJECT_EXPLANATION) NOT LIKE '%BİLEŞEN %'
                    AND UPPER(TDCRCI.SUBJECT_EXPLANATION) NOT LIKE '%BILESEN%')
                AND TDCRCI.CREATE_DATE >= TO_DATE('{start_date}', 'DD.MM.YYYY')
                AND TDCRCI.CREATE_DATE < TO_DATE('{end_date}', 'DD.MM.YYYY')
            GROUP BY TDCRCI.FIRM_CODE) T2 ON T1.FIRM_CODE = T2.FIRM_CODE
    """
    cursor = connection.cursor()
    cursor.execute(query)

    results = cursor.fetchall()
    workOrder_count = 0
    contact_count = 0
    for res in results:
        try:workOrder_count = workOrder_count + res[1]
        except:pass
        try:contact_count = contact_count + res[2]
        except:pass


    return workOrder_count, contact_count

