import oracledb
import os
import pandas as pd
from config import dsn
from datetime import datetime, timedelta


def return_sabahraporu_islemalti():
    connection = oracledb.connect(dsn)
    query= """
        SELECT SUM (PENDING_INVOICES)
        FROM YUCE_DM.TBL_DW_VEH_RPT_VEHICLE_SALES_CONNECTION_MANAGEMENT
        WHERE ENTRY_DATE = (SELECT MAX(ENTRY_DATE) FROM YUCE_DM.TBL_DW_VEH_RPT_VEHICLE_SALES_CONNECTION_MANAGEMENT)
    """
    cursor = connection.cursor()
    cursor.execute(query)
    result = cursor.fetchall()
    return result[0][0]

def return_sabahraporu_bugunolasilik():
    connection = oracledb.connect(dsn)
    query1 = """
        SELECT SUM (EXPECTED_INVOICES)
        FROM YUCE_DM.TBL_DW_VEH_RPT_VEHICLE_SALES_CONNECTION_MANAGEMENT
        WHERE ENTRY_DATE = (SELECT MAX(ENTRY_DATE) FROM YUCE_DM.TBL_DW_VEH_RPT_VEHICLE_SALES_CONNECTION_MANAGEMENT)
    """
    cursor = connection.cursor()
    cursor.execute(query1)
    result1 = cursor.fetchall()
    return result1[0][0]

def return_sabahraporu_bugunperakende():
    connection = oracledb.connect(dsn)
    query1 = """
        SELECT SUM (CONFIRMED_INVOICES)
        FROM YUCE_DM.TBL_DW_VEH_RPT_VEHICLE_SALES_CONNECTION_MANAGEMENT
        WHERE ENTRY_DATE = (SELECT MAX(ENTRY_DATE) FROM YUCE_DM.TBL_DW_VEH_RPT_VEHICLE_SALES_CONNECTION_MANAGEMENT)
    """
    cursor = connection.cursor()
    cursor.execute(query1)
    result = cursor.fetchall()
    return result[0][0]

def return_sabahraporu_digersatislar_filo():
    yesterday = datetime.now().month
    connection = oracledb.connect(dsn)
    query1 = """
        SELECT
        COUNT(DISTINCT YUCE_DM.TBL_DW_VEH_VEHICLE.CHASSIS) AS CHASSIS_COUNT,
        -- SUM(CASE WHEN EXTRACT(YEAR FROM ACTIVITY_DATE) = EXTRACT(YEAR FROM SYSDATE) - 1 THEN COUNT_CHASSIS ELSE 0 END) AS PRV_YEAR_COUNT_CHASSIS,
        -- SUM(CASE WHEN EXTRACT(YEAR FROM ACTIVITY_DATE) = EXTRACT(YEAR FROM SYSDATE) THEN COUNT_CHASSIS ELSE 0 END) AS THIS_YEAR_COUNT_CHASSIS,
        -- EXTRACT(YEAR FROM YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_YS."DATE") AS ACTIVITY_YEAR,
            --EXTRACT(MONTH FROM YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_YS."DATE"),

            EXTRACT (MONTH FROM YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_DS."DATE") AS "Month",
                EXTRACT (YEAR FROM YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_DS."DATE") AS "Year"
            --YUCE_DM.TBL_DW_VEH_RPT_VEHICLE_STATUS.RESERVE
        FROM
        YUCE_DM.TBL_DW_VEH_STOCK_ACTIVITY  YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_DS RIGHT OUTER JOIN YUCE_DM.TBL_DW_VEH_VEHICLE ON (YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_DS.VEHICLE_ID=YUCE_DM.TBL_DW_VEH_VEHICLE.VEHICLE_ID AND YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_DS.ACTIVITY_TYPE = 13 )
        INNER JOIN YUCE_DM.TBL_DW_VEH_RPT_VEHICLE_STATUS ON (YUCE_DM.TBL_DW_VEH_VEHICLE.VEHICLE_ID=YUCE_DM.TBL_DW_VEH_RPT_VEHICLE_STATUS.VEHICLE_ID )
        WHERE
        EXTRACT (YEAR FROM  YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_DS."DATE" )= EXTRACT (YEAR FROM SYSDATE)
        AND (YUCE_DM.TBL_DW_VEH_RPT_VEHICLE_STATUS.RESERVE IN ('FİLO Rezervli') OR YUCE_DM.TBL_DW_VEH_RPT_VEHICLE_STATUS.RESERVE IS NULL)

        GROUP BY 
        -- EXTRACT(YEAR FROM YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_YS."DATE"),
        --     EXTRACT(MONTH FROM YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_YS."DATE"),
            EXTRACT (YEAR FROM YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_DS."DATE"),
                EXTRACT (MONTH FROM YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_DS."DATE")
        -- YUCE_DM.TBL_DW_VEH_RPT_VEHICLE_STATUS.RESERVE
        ORDER BY 
        EXTRACT (MONTH FROM YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_DS."DATE")
    """
    cursor = connection.cursor()
    cursor.execute(query1)
    result = cursor.fetchall()
    
    annual_sum = 0
    thismonth_sum = 0

    for row in result:
        if row[1] == yesterday:
            thismonth_sum = row[0]
        else:
            thismonth_sum = 0
        annual_sum = annual_sum + row[0]
    return thismonth_sum, annual_sum

def return_sabahraporu_digersatislar_perakende():
    today = datetime.now().month
    connection = oracledb.connect(dsn)
    query1 = """
        SELECT
        COUNT(DISTINCT YUCE_DM.TBL_DW_VEH_VEHICLE.CHASSIS) AS CHASSIS_COUNT,
        -- SUM(CASE WHEN EXTRACT(YEAR FROM ACTIVITY_DATE) = EXTRACT(YEAR FROM SYSDATE) - 1 THEN COUNT_CHASSIS ELSE 0 END) AS PRV_YEAR_COUNT_CHASSIS,
        -- SUM(CASE WHEN EXTRACT(YEAR FROM ACTIVITY_DATE) = EXTRACT(YEAR FROM SYSDATE) THEN COUNT_CHASSIS ELSE 0 END) AS THIS_YEAR_COUNT_CHASSIS,
        -- EXTRACT(YEAR FROM YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_YS."DATE") AS ACTIVITY_YEAR,
            --EXTRACT(MONTH FROM YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_YS."DATE"),

            EXTRACT (MONTH FROM YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_DS."DATE") AS "Month",
                EXTRACT (YEAR FROM YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_DS."DATE") AS "Year"
            --YUCE_DM.TBL_DW_VEH_RPT_VEHICLE_STATUS.RESERVE
        FROM
        YUCE_DM.TBL_DW_VEH_STOCK_ACTIVITY  YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_DS RIGHT OUTER JOIN YUCE_DM.TBL_DW_VEH_VEHICLE ON (YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_DS.VEHICLE_ID=YUCE_DM.TBL_DW_VEH_VEHICLE.VEHICLE_ID AND YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_DS.ACTIVITY_TYPE = 13 )
        INNER JOIN YUCE_DM.TBL_DW_VEH_RPT_VEHICLE_STATUS ON (YUCE_DM.TBL_DW_VEH_VEHICLE.VEHICLE_ID=YUCE_DM.TBL_DW_VEH_RPT_VEHICLE_STATUS.VEHICLE_ID )
        WHERE
        EXTRACT (YEAR FROM  YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_DS."DATE" )= EXTRACT (YEAR FROM SYSDATE)
        AND (YUCE_DM.TBL_DW_VEH_RPT_VEHICLE_STATUS.RESERVE NOT IN ('FİLO Rezervli') OR YUCE_DM.TBL_DW_VEH_RPT_VEHICLE_STATUS.RESERVE IS NULL)

        GROUP BY 
        -- EXTRACT(YEAR FROM YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_YS."DATE"),
        --     EXTRACT(MONTH FROM YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_YS."DATE"),
            EXTRACT (YEAR FROM YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_DS."DATE"),
                EXTRACT (MONTH FROM YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_DS."DATE")
        -- YUCE_DM.TBL_DW_VEH_RPT_VEHICLE_STATUS.RESERVE
        ORDER BY 
        EXTRACT (MONTH FROM YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_DS."DATE")
    """
    cursor = connection.cursor()
    cursor.execute(query1)
    result = cursor.fetchall()

    annual_sum = 0
    thismonth_sum = 0

    for row in result:
        if row[1] == today:
            thismonth_sum = row[0]
        else:
            thismonth_sum = 0
        annual_sum = annual_sum + row[0]
    return thismonth_sum, annual_sum

def return_sabahraporu_filo_adetler():
    today = datetime.now().month
    connection = oracledb.connect(dsn)
    query1 = """
    SELECT
    COUNT(DISTINCT YUCE_DM.TBL_DW_VEH_VEHICLE.CHASSIS) AS CHASSIS_COUNT,
    -- SUM(CASE WHEN EXTRACT(YEAR FROM ACTIVITY_DATE) = EXTRACT(YEAR FROM SYSDATE) - 1 THEN COUNT_CHASSIS ELSE 0 END) AS PRV_YEAR_COUNT_CHASSIS,
    -- SUM(CASE WHEN EXTRACT(YEAR FROM ACTIVITY_DATE) = EXTRACT(YEAR FROM SYSDATE) THEN COUNT_CHASSIS ELSE 0 END) AS THIS_YEAR_COUNT_CHASSIS,
    -- EXTRACT(YEAR FROM YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_YS."DATE") AS ACTIVITY_YEAR,
        --EXTRACT(MONTH FROM YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_YS."DATE"),

        EXTRACT (MONTH FROM YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_YS."DATE") AS "Month",
            EXTRACT (YEAR FROM YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_YS."DATE") AS "Year"
        --YUCE_DM.TBL_DW_VEH_RPT_VEHICLE_STATUS.RESERVE
    FROM
    YUCE_DM.TBL_DW_VEH_STOCK_ACTIVITY  YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_YS RIGHT OUTER JOIN YUCE_DM.TBL_DW_VEH_VEHICLE ON (YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_YS.VEHICLE_ID=YUCE_DM.TBL_DW_VEH_VEHICLE.VEHICLE_ID AND YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_YS.ACTIVITY_TYPE = 8 )
    INNER JOIN YUCE_DM.TBL_DW_VEH_RPT_VEHICLE_STATUS ON (YUCE_DM.TBL_DW_VEH_VEHICLE.VEHICLE_ID=YUCE_DM.TBL_DW_VEH_RPT_VEHICLE_STATUS.VEHICLE_ID )
    WHERE
    EXTRACT (YEAR FROM  YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_YS."DATE" )= EXTRACT (YEAR FROM SYSDATE)
    AND YUCE_DM.TBL_DW_VEH_RPT_VEHICLE_STATUS.RESERVE IN ('FİLO Rezervli') --OR YUCE_DM.TBL_DW_VEH_RPT_VEHICLE_STATUS.RESERVE IS NOT NULL

    GROUP BY 
    -- EXTRACT(YEAR FROM YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_YS."DATE"),
    --     EXTRACT(MONTH FROM YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_YS."DATE"),
        EXTRACT (YEAR FROM YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_YS."DATE"),
            EXTRACT (MONTH FROM YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_YS."DATE")
    -- YUCE_DM.TBL_DW_VEH_RPT_VEHICLE_STATUS.RESERVE
    ORDER BY 
    EXTRACT (MONTH FROM YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_YS."DATE")

    """
    
    cursor = connection.cursor()
    cursor.execute(query1)
    result = cursor.fetchall()
    annual_sum = 0
    thismonth_sum = 0

    for row in result:
        if row[1] == today:
            thismonth_sum = row[0]
        else:
            thismonth_sum = 0
        annual_sum = annual_sum + row[0]
    return thismonth_sum, annual_sum

def return_sabahraporu_perakende_adetler():
    today = datetime.now().month
    connection = oracledb.connect(dsn)
    query1 = """
    SELECT
    COUNT(DISTINCT YUCE_DM.TBL_DW_VEH_VEHICLE.CHASSIS) AS CHASSIS_COUNT,
    EXTRACT(MONTH FROM YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_YS."DATE") AS "Month",
    EXTRACT(YEAR FROM YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_YS."DATE") AS "Year"
    FROM
    YUCE_DM.TBL_DW_VEH_STOCK_ACTIVITY YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_YS
    RIGHT OUTER JOIN YUCE_DM.TBL_DW_VEH_VEHICLE ON (YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_YS.VEHICLE_ID = YUCE_DM.TBL_DW_VEH_VEHICLE.VEHICLE_ID AND YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_YS.ACTIVITY_TYPE = 8)
    INNER JOIN YUCE_DM.TBL_DW_VEH_RPT_VEHICLE_STATUS ON (YUCE_DM.TBL_DW_VEH_VEHICLE.VEHICLE_ID = YUCE_DM.TBL_DW_VEH_RPT_VEHICLE_STATUS.VEHICLE_ID)
    WHERE
    EXTRACT(YEAR FROM YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_YS."DATE") IN EXTRACT(YEAR FROM SYSDATE) -- Sadece geçerli yılın verilerini al
    AND (YUCE_DM.TBL_DW_VEH_RPT_VEHICLE_STATUS.RESERVE NOT IN ('FİLO Rezervli') OR YUCE_DM.TBL_DW_VEH_RPT_VEHICLE_STATUS.RESERVE IS NULL)
    GROUP BY
    EXTRACT(YEAR FROM YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_YS."DATE"),
    EXTRACT(MONTH FROM YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_YS."DATE")
    ORDER BY
    EXTRACT(YEAR FROM YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_YS."DATE"),
    EXTRACT(MONTH FROM YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_YS."DATE")
    """
    
    cursor = connection.cursor()
    cursor.execute(query1)
    result = cursor.fetchall()
    annual_sum = 0
    thismonth_sum = 0

    for row in result:
        if row[1] == today:
            thismonth_sum = row[0]
        else:
            thismonth_sum = 0
        annual_sum = annual_sum + row[0]
    return thismonth_sum, annual_sum

def return_sabahraporu_toptan_filo_adetler():
    today = datetime.now().month
    connection = oracledb.connect(dsn)
    query1 = """
    SELECT
    COUNT(DISTINCT YUCE_DM.TBL_DW_VEH_VEHICLE.CHASSIS) AS CHASSIS_COUNT,
    -- SUM(CASE WHEN EXTRACT(YEAR FROM ACTIVITY_DATE) = EXTRACT(YEAR FROM SYSDATE) - 1 THEN COUNT_CHASSIS ELSE 0 END) AS PRV_YEAR_COUNT_CHASSIS,
    -- SUM(CASE WHEN EXTRACT(YEAR FROM ACTIVITY_DATE) = EXTRACT(YEAR FROM SYSDATE) THEN COUNT_CHASSIS ELSE 0 END) AS THIS_YEAR_COUNT_CHASSIS,
    -- EXTRACT(YEAR FROM YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_YS."DATE") AS ACTIVITY_YEAR,
        --EXTRACT(MONTH FROM YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_YS."DATE"),

        EXTRACT (MONTH FROM YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_DS."DATE") AS "Month",
            EXTRACT (YEAR FROM YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_DS."DATE") AS "Year"
        --YUCE_DM.TBL_DW_VEH_RPT_VEHICLE_STATUS.RESERVE
    FROM
    YUCE_DM.TBL_DW_VEH_STOCK_ACTIVITY  YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_DS RIGHT OUTER JOIN YUCE_DM.TBL_DW_VEH_VEHICLE ON (YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_DS.VEHICLE_ID=YUCE_DM.TBL_DW_VEH_VEHICLE.VEHICLE_ID AND YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_DS.ACTIVITY_TYPE = 4 )
    INNER JOIN YUCE_DM.TBL_DW_VEH_RPT_VEHICLE_STATUS ON (YUCE_DM.TBL_DW_VEH_VEHICLE.VEHICLE_ID=YUCE_DM.TBL_DW_VEH_RPT_VEHICLE_STATUS.VEHICLE_ID )
    WHERE
    EXTRACT (YEAR FROM  YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_DS."DATE" )= EXTRACT (YEAR FROM SYSDATE)
    AND YUCE_DM.TBL_DW_VEH_RPT_VEHICLE_STATUS.RESERVE IN ('FİLO Rezervli') --OR YUCE_DM.TBL_DW_VEH_RPT_VEHICLE_STATUS.RESERVE IS NOT NULL

    GROUP BY 
    -- EXTRACT(YEAR FROM YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_YS."DATE"),
    --     EXTRACT(MONTH FROM YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_YS."DATE"),
        EXTRACT (YEAR FROM YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_DS."DATE"),
            EXTRACT (MONTH FROM YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_DS."DATE")
    -- YUCE_DM.TBL_DW_VEH_RPT_VEHICLE_STATUS.RESERVE
    ORDER BY 
    EXTRACT (MONTH FROM YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_DS."DATE")
    """
    cursor = connection.cursor()
    cursor.execute(query1)
    result = cursor.fetchall()
    annual_sum = 0
    thismonth_sum = 0

    for row in result:
        if row[1] == today:
            thismonth_sum = row[0]
        else:
            thismonth_sum = 0
        annual_sum = annual_sum + row[0]
    return thismonth_sum, annual_sum

def return_sabahraporu_toptan_perakende_adetler():
    today = datetime.now().month
    connection = oracledb.connect(dsn)
    query1 = """
    SELECT
    COUNT(DISTINCT YUCE_DM.TBL_DW_VEH_VEHICLE.CHASSIS) AS CHASSIS_COUNT,
    -- SUM(CASE WHEN EXTRACT(YEAR FROM ACTIVITY_DATE) = EXTRACT(YEAR FROM SYSDATE) - 1 THEN COUNT_CHASSIS ELSE 0 END) AS PRV_YEAR_COUNT_CHASSIS,
    -- SUM(CASE WHEN EXTRACT(YEAR FROM ACTIVITY_DATE) = EXTRACT(YEAR FROM SYSDATE) THEN COUNT_CHASSIS ELSE 0 END) AS THIS_YEAR_COUNT_CHASSIS,
    -- EXTRACT(YEAR FROM YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_YS."DATE") AS ACTIVITY_YEAR,
        --EXTRACT(MONTH FROM YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_YS."DATE"),

        EXTRACT (MONTH FROM YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_DS."DATE") AS "Month",
            EXTRACT (YEAR FROM YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_DS."DATE") AS "Year"
        --YUCE_DM.TBL_DW_VEH_RPT_VEHICLE_STATUS.RESERVE
    FROM
    YUCE_DM.TBL_DW_VEH_STOCK_ACTIVITY  YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_DS RIGHT OUTER JOIN YUCE_DM.TBL_DW_VEH_VEHICLE ON (YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_DS.VEHICLE_ID=YUCE_DM.TBL_DW_VEH_VEHICLE.VEHICLE_ID AND YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_DS.ACTIVITY_TYPE = 4 )
    INNER JOIN YUCE_DM.TBL_DW_VEH_RPT_VEHICLE_STATUS ON (YUCE_DM.TBL_DW_VEH_VEHICLE.VEHICLE_ID=YUCE_DM.TBL_DW_VEH_RPT_VEHICLE_STATUS.VEHICLE_ID )
    WHERE
    EXTRACT (YEAR FROM  YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_DS."DATE" )= EXTRACT (YEAR FROM SYSDATE)
    AND (YUCE_DM.TBL_DW_VEH_RPT_VEHICLE_STATUS.RESERVE NOT IN ('FİLO Rezervli') OR YUCE_DM.TBL_DW_VEH_RPT_VEHICLE_STATUS.RESERVE IS NULL)

    GROUP BY 
    -- EXTRACT(YEAR FROM YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_YS."DATE"),
    --     EXTRACT(MONTH FROM YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_YS."DATE"),
        EXTRACT (YEAR FROM YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_DS."DATE"),
            EXTRACT (MONTH FROM YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_DS."DATE")
    -- YUCE_DM.TBL_DW_VEH_RPT_VEHICLE_STATUS.RESERVE
    ORDER BY 
    EXTRACT (MONTH FROM YUCE_DM_TBL_DW_VEH_STOCK_ACTIVITY_DS."DATE")
    """
    cursor = connection.cursor()
    cursor.execute(query1)
    result = cursor.fetchall()
    annual_sum = 0
    thismonth_sum = 0

    for row in result:
        if row[1] == today:
            thismonth_sum = row[0]
        else:
            thismonth_sum = 0
        annual_sum = annual_sum + row[0]
    return thismonth_sum, annual_sum

def return_sabahraporu_firsttable_astuple():
    connection = oracledb.connect(dsn)

    query1 = """
        ----SADECE PERAKENDENİN MÜŞTERİLERİNİ AL 
    SELECT 
    CASE 
        WHEN YUCE_DM.TBL_DW_VEH_RPT_VEHICLE_STATUS.OEM_STATUS_EXPLANATION IN ('Faturalandı', 'YSStok') THEN 'YSStok'
        WHEN YUCE_DM.TBL_DW_VEH_RPT_VEHICLE_STATUS.OEM_STATUS_EXPLANATION IN ('Produced', 'IntTransfer') THEN 'Produced & Int'
        ELSE YUCE_DM.TBL_DW_VEH_RPT_VEHICLE_STATUS.OEM_STATUS_EXPLANATION
    END AS Statü,

    COUNT(DISTINCT YUCE_DM.TBL_DW_VEH_ORDER.ORDER_NO) AS DISTINCT_ORDER_COUNT,
    COUNT(DISTINCT CASE WHEN YUCE_DM.TBL_DW_VEH_RPT_VEHICLE_STATUS.RELATED_CUSTOMER IS NOT NULL THEN YUCE_DM.TBL_DW_VEH_ORDER.ORDER_NO END) AS NON_NULL_CUSTOMER_COUNT,
    CASE 
        WHEN YUCE_DM.TBL_DW_VEH_RPT_VEHICLE_STATUS.RESERVE = 'FİLO Rezervli' THEN 'Filo'
        ELSE 'Perakende'
    END AS RESERVE_CATEGORY
    FROM

    YUCE_DM.TBL_DW_VEH_RPT_VEHICLE_STATUS 
    LEFT JOIN YUCE_DM.TBL_DW_VEH_VEHICLE ON (YUCE_DM.TBL_DW_VEH_VEHICLE.VEHICLE_ID=YUCE_DM.TBL_DW_VEH_RPT_VEHICLE_STATUS.VEHICLE_ID)
    LEFT JOIN YUCE_DM.TBL_DW_VEH_MODEL_CATALOG ON (YUCE_DM.TBL_DW_VEH_MODEL_CATALOG.COUNTRYMODEL_ID=YUCE_DM.TBL_DW_VEH_VEHICLE.FK_COUNTRYMODEL_ID)
    LEFT JOIN YUCE_DM.TBL_DW_VEH_STOCK_ACTIVITY ON (YUCE_DM.TBL_DW_VEH_STOCK_ACTIVITY.VEHICLE_ID=YUCE_DM.TBL_DW_VEH_VEHICLE.VEHICLE_ID)
    LEFT JOIN YUCE_DM.TBL_DW_VEH_ORDER ON (YUCE_DM.TBL_DW_VEH_VEHICLE.ORDER_ID=YUCE_DM.TBL_DW_VEH_ORDER.ORDER_ID)
    LEFT JOIN YUCE_DM.TBL_DW_VEH_DIM_DS_SALES_TYPE  DS_SALES_TYPE ON (DS_SALES_TYPE.DS_SALES_TYPE_ID=YUCE_DM.TBL_DW_VEH_VEHICLE.LAST_DS_SALES_TYPE)
    WHERE
    DS_SALES_TYPE.DS_SALES_TYPE_EXPLANATION NOT IN ('Antrepo Eşya Satışı', 'Mavi Plaka', 'Perakende')
    AND YUCE_DM.TBL_DW_VEH_RPT_VEHICLE_STATUS.OEM_STATUS_EXPLANATION IN ('YSStok', 'Faturalandı', 'Fatura Bekliyor', 'Yolda', 'Stok', 'Fiktif', 'Transport', 'IntTransfer', 'Liman', 'Produced')

    GROUP BY
    CASE 
        WHEN YUCE_DM.TBL_DW_VEH_RPT_VEHICLE_STATUS.OEM_STATUS_EXPLANATION IN ('Faturalandı', 'YSStok') THEN 'YSStok'
        WHEN YUCE_DM.TBL_DW_VEH_RPT_VEHICLE_STATUS.OEM_STATUS_EXPLANATION IN ('Produced', 'IntTransfer') THEN 'Produced & Int'
        ELSE YUCE_DM.TBL_DW_VEH_RPT_VEHICLE_STATUS.OEM_STATUS_EXPLANATION
    END,
    CASE 
        WHEN YUCE_DM.TBL_DW_VEH_RPT_VEHICLE_STATUS.RESERVE = 'FİLO Rezervli' THEN 'Filo'
        ELSE 'Perakende'
    END
    ORDER BY
    CASE 
        WHEN YUCE_DM.TBL_DW_VEH_RPT_VEHICLE_STATUS.RESERVE = 'FİLO Rezervli' THEN 'Filo'
        ELSE 'Perakende'
    END
        
        """

    cursor = connection.cursor()
    cursor.execute(query1)
    result1 = cursor.fetchall()
    return result1

def return_sabahraporu_secondtable_astuple():
    connection = oracledb.connect(dsn)

    query = """
        SELECT
        YUCE_DM.TBL_DW_VEH_MODEL_CATALOG.TOPMODEL_DEFINITION,
        COUNT(DISTINCT YUCE_DM.TBL_DW_VEH_ORDER.ORDER_NO) AS DISTINCT_ORDER_COUNT,
        COUNT(DISTINCT CASE WHEN YUCE_DM.TBL_DW_VEH_RPT_VEHICLE_STATUS.RELATED_CUSTOMER IS NOT NULL THEN YUCE_DM.TBL_DW_VEH_ORDER.ORDER_NO END) AS NON_NULL_CUSTOMER_COUNT,
        CASE
            WHEN YUCE_DM.TBL_DW_VEH_RPT_VEHICLE_STATUS.RESERVE = 'FİLO Rezervli' THEN 'Filo'
            ELSE 'Perakende'
        END AS RESERVE_CATEGORY
    FROM
        YUCE_DM.TBL_DW_VEH_RPT_VEHICLE_STATUS
    LEFT JOIN YUCE_DM.TBL_DW_VEH_VEHICLE ON YUCE_DM.TBL_DW_VEH_VEHICLE.VEHICLE_ID = YUCE_DM.TBL_DW_VEH_RPT_VEHICLE_STATUS.VEHICLE_ID
    LEFT JOIN YUCE_DM.TBL_DW_VEH_MODEL_CATALOG ON YUCE_DM.TBL_DW_VEH_MODEL_CATALOG.COUNTRYMODEL_ID = YUCE_DM.TBL_DW_VEH_VEHICLE.FK_COUNTRYMODEL_ID
    LEFT JOIN YUCE_DM.TBL_DW_VEH_STOCK_ACTIVITY ON YUCE_DM.TBL_DW_VEH_STOCK_ACTIVITY.VEHICLE_ID = YUCE_DM.TBL_DW_VEH_VEHICLE.VEHICLE_ID
    LEFT JOIN YUCE_DM.TBL_DW_VEH_ORDER ON YUCE_DM.TBL_DW_VEH_VEHICLE.ORDER_ID = YUCE_DM.TBL_DW_VEH_ORDER.ORDER_ID
    LEFT JOIN YUCE_DM.TBL_DW_VEH_DIM_DS_SALES_TYPE DS_SALES_TYPE ON DS_SALES_TYPE.DS_SALES_TYPE_ID = YUCE_DM.TBL_DW_VEH_VEHICLE.LAST_DS_SALES_TYPE
    WHERE
        DS_SALES_TYPE.DS_SALES_TYPE_EXPLANATION NOT IN ('Antrepo Eşya Satışı', 'Mavi Plaka', 'Perakende')
        AND YUCE_DM.TBL_DW_VEH_RPT_VEHICLE_STATUS.OEM_STATUS_EXPLANATION IN ('YSStok', 'Faturalandı', 'Fatura Bekliyor')
    GROUP BY
        YUCE_DM.TBL_DW_VEH_MODEL_CATALOG.TOPMODEL_DEFINITION,
        CASE
            WHEN YUCE_DM.TBL_DW_VEH_RPT_VEHICLE_STATUS.RESERVE = 'FİLO Rezervli' THEN 'Filo'
            ELSE 'Perakende'
        END
        
        ORDER BY
    CASE
            WHEN YUCE_DM.TBL_DW_VEH_RPT_VEHICLE_STATUS.RESERVE = 'FİLO Rezervli' THEN 'Filo'
            ELSE 'Perakende'
        END
    """

    cursor = connection.cursor()
    cursor.execute(query)

    result1 = cursor.fetchall()
    
    return result1
